
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxgieoboxkexaksqpfgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4Z2llb2JveGtleGFrc3FwZmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMzI1NTcsImV4cCI6MjA1NDcwODU1N30.GW_Y4EWq2BsQjSPZrydV0KxxtG5_V14OaTT8NFiEj4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
